### ISSUE TITLE
Unable to import woma

### ISSUE THREAD

**Issue by burgerz0** [srbonilla/WoMa#14]
" ModuleNotFoundError: No module named 'scipy' "

**Comment by Francyrad** [comment]
Or you didn't install scipy or you installed woma in a different python version.

Try 

pip3 install scipy 

or 

pip install scipy

or

pip3.9 install scipy
where 3.9 is the python version, so you can change the numbers according to the version you are using

**Comment by burgerz0** [comment]
Oh that fixed it, thanks
