### ISSUE TITLE
WoMa speed values are different from post added speed values. Conversion error?

### ISSUE THREAD

**Issue by Francyrad** [srbonilla/WoMa#15]
Dear developers
I was doing some experiments about balancing the momentum of my simulations in post processing instead of doing that with WoMa.
I was also doing some experiments like adding velocities to my impact system, for example, a vx of -29785 m/s both with a script in a free system and with WoMa in way that these bodies have a real velocity in the simulation.

but there is a problem

When i extract these values with python:
```
    data = sw.load(snapshot)
    vel = np.array(data.gas.velocities)
    data.gas.velocities.convert_to_mks()
```
I got a value (true for me) in the case where my system has a velocity scripted with WoMa (which is of -3.23e4 m/s) and totally another value when i want to add this velocity in post processing with python. 

Specifically, i used in SwiftSim a value of 1e8g and 1e8s

So, if i want to add a speed of -29785 m/s, i should divide it for 1e6 ((1e8/6.371e8)*6.371e6))

anyway, when my results are plotted, i got a speed of -3.14e4 m/s instead of -3.24e4 m/s, which for me should be the true value. 

Why this happens? Am I doing a wrong conversion? Am I missing something? Because i was thinking just to manipulate a simulation without balancing anything and then adding velocities to simulate orbital speeds of my asteroids (and then track the fragments in other way), but if the values added in post processing are not correct i must do thousands simulations with different speeds

Thank you for the availability and your work

**Comment by jkeger** [comment]
Hi Francesco, thanks for the question, I've emailed you to ask for some more details and with a suggestion for a closer to minimal working example test to start with.

**Comment by Francyrad** [comment]
Issue solved

**Comment by Francyrad** [comment]
Hi Jacob, I must reopen the issue because i can't find any logic in that...
I just did this experiment on a system without any balancing:

```
data = sw.load(snapshot)
    box_mid = 0.5 * data.metadata.boxsize[0].to(unyt.m)
    pos = data.gas.coordinates.to(unyt.m) - box_mid
    pos = np.array(pos)
    vel = np.array(data.gas.velocities)
    data.gas.velocities.convert_to_mks()
    data.gas.masses.convert_to_mks()
    m = np.array(data.gas.masses)
    data.gas.masses.convert_to_mks()
    #vel[:, 0] += -29785/(1e6)
    sum_vel_x = np.sum(vel[:, 0])
    sum_vel_y = np.sum(vel[:, 1])
    sum_vel_z = np.sum(vel[:, 2])

    print("velocity sum in x, y e z:", sum_vel_x, sum_vel_y, sum_vel_z)
    vel[:, 0] += -29785/(1e6)
    sum_vel_x = np.sum(vel[:, 0])
    sum_vel_y = np.sum(vel[:, 1])
    sum_vel_z = np.sum(vel[:, 2])
    print("velocity sum in x, y e z:", sum_vel_x, sum_vel_y, sum_vel_z)
 ```
    
I'm running on 1e8 speed system:

```
    InternalUnitSystem:
    UnitMass_in_cgs:        1e27        # Sets Earth mass = 5.972
    UnitLength_in_cgs:      1e8         # Sets Earth radius = 6.371
    UnitVelocity_in_cgs:    1e8         # Sets time in seconds
    UnitCurrent_in_cgs:     1           # Amperes
    UnitTemp_in_cgs:        1           # Kelvin
```
    
According to the logic, I should get X as result. For the second result, i should get x -29785
    
Instead, i get:
  
```
velocity sum in x, y e z: -907.93823 -20.040203 0.454216
velocity sum in x, y e z: -32282.625 -20.040203 0.454216
```

The point is that -907 -29785 = -30692 and not -32282.625

I get the same result if both bodies have a speed of -29785 m/s added by Woma
it's not an issue related to h_max, any h_max produce the same result...

So, if this -29785 m/s speed is already inside the simulation and is been added by WoMa, when I analyze the data i got a sum speed of :
```
velocity sum in x, y e z: -32282.625 -20.040203 0.454216
```
If i subtract:
```
vel[:, 0] += +29785/(1e6)
```
and then:
```
sum_vel_x = np.sum(vel[:, 0])
sum_vel_y = np.sum(vel[:, 1])
sum_vel_z = np.sum(vel[:, 2])
print("velocity sum in x, y e z:", sum_vel_x, sum_vel_y, sum_vel_z)
```
I get:
```
velocity sum in x, y e z: -907.93823 -20.040203 0.454216
```


So my answer is one: i'm extracting the results in a wrong way? I'm I doing something wrong? I'm extracting wrong data? Is there a bug?

Thank you for the help
Francesco

**Comment by Francyrad** [comment]
Edit:
I discovered that the vel data printed from my simulations are partially wrong.

I had to do some proportions to discover that. For example, If i want to add a speed of -29785 m/s to my simulation, i don't have to:
`vel[:, 0] += -29785/(1e6)`

but i first need to add a conversion factor, which doing some tries i discovered to be:
`conversion_factor = 1053372.056`

then i can perfectly add a speed of -29785 m/s if i divide the speed by this number:

`vel[:, 0] += -29785/ conversion_factor`

But I don't get that, because the sim is supposed to have a scale of 1e8 cm/s.

Because also the velocity data that python extract are wrong (because if I have in a simulation a total speed of -29785 m/s added by WoMa, I got the same result of adding a speed of vel[:, 0] += -29785/(1e6) into the sim (-31374 m/s), to get correct speed i need to multiply the vel array for this number:

```
conversion_factor_vel = 0.9493321868
vel = np.array(data.gas.velocities) * conversion_factor_vel

```
In this way I can get accurate velocities

My question is: why python (swiftsimio? unyt? WoMa?) has this conversions issues, is it a bug or i'm doing something wrong?

Thank you for the availability and help
Francesco.

**Comment by Francyrad** [comment]
There is no bug. Simply adding a speed with vel[:, 0] += -29785 in vx doesn't mean that the bodies of the system will have that speed if you summon it with the sum of the speed. The user must summon the speed of the center of mass to see the correct value.

I'm sorry for the waste of time
